name: aiplantidentifier
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  avatar_glow: ^2.0.1
  image_picker: ^1.1.2
  intl: ^0.18.1
  image: ^4.7.2
  dotted_border: ^2.1.0
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  uuid: ^4.5.1
  collection: ^1.19.1
  font_awesome_flutter: ^10.8.0
  fl_chart: ^0.64.0
  flutter_markdown: ^0.6.18
  shimmer: ^3.0.0
  percent_indicator: ^4.2.3
  confetti: ^0.8.0
  badges: ^3.1.2
  google_fonts: ^4.0.5
  flutter_typeahead: ^5.2.0
  flutter_animate: ^4.5.2
  flash_card: ^0.1.0
  flutter_chat_bubble: ^2.0.2
  flutter_spinkit: ^5.2.1
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  path: ^1.8.3
  syncfusion_flutter_charts: ^29.1.40
  water_drop_nav_bar: ^2.2.2
  syncfusion_flutter_gauges: ^29.1.40
  mobile_scanner: ^7.0.0
  shared_preferences: ^2.5.3
  mysql1: ^0.20.0
  connectivity_plus: ^7.0.0
  logger: ^2.6.2
  fluttertoast: ^8.1.0
  flutter_svg: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "images/app_logo.png"

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "images/app_logo.png"

  # iOS (no transparency allowed)
  remove_alpha_ios: true
  background_color_ios: "#4CAF50"

  # Android (adaptive icon)
  adaptive_icon_background: "#4CAF50"
  adaptive_icon_foreground: "images/app_logo.png"
